/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import model.Config;
import model.Measure;
import model.Setting;
import io.ReadLog;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @TempDir
    Path tempDir;

    @Test
    void readLogParsesQuotedAndPlainTimestamps() throws Exception {
        Path logFile = tempDir.resolve("log.json");
        String line1 = "{\"time\":\"2026-01-31 00:00:00.000\",\"source\":\"s\",\"rc\":[{\"measure\":\"m\",\"value\":1,\"tag\":\"t\",\"alert\":false}]}";
        String line2 = "{\"time\":\"\\\"2026-01-31 00:00:01.000\\\"\",\"source\":\"s\",\"rc\":[{\"measure\":\"m\",\"value\":2,\"tag\":\"t\",\"alert\":false}]}";
        Files.writeString(logFile, line1 + "\n" + line2 + "\n", StandardCharsets.UTF_8);

        Setting setting = new Setting();
        Measure[] measures = new Measure[] {
            new Measure("m", false, 0, 0, "select 1", "t", false, null, false)
        };
        Config config = new Config(setting, measures);
        Gson gson = new GsonBuilder().setLenient().create();

        ReadLog rl = new ReadLog(logFile.toFile(), gson, config);
        assertEquals(2, rl.timeMap.size());
        rl.setNameMap("m");
        assertEquals(2, rl.nameMap.size());
        rl.nameMap.values().forEach(rcs -> assertNotNull(rcs[0]));
    }
}
